"""Added quantity column

Revision ID: 10637c7d7537
Revises: 1f5c60222ccf
Create Date: 2025-02-28 05:20:58.762175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10637c7d7537'
down_revision: Union[str, None] = '1f5c60222ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'quantity')
    # ### end Alembic commands ###
