"""Added label column

Revision ID: 1eebf08b53d7
Revises: 99ce0f4ca2c7
Create Date: 2025-02-28 06:30:01.215407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eebf08b53d7'
down_revision: Union[str, None] = '99ce0f4ca2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'label')
    # ### end Alembic commands ###
