"""Added section column

Revision ID: 7db7efdce183
Revises: c35afc6a1e4d
Create Date: 2025-02-28 05:51:04.509496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db7efdce183'
down_revision: Union[str, None] = 'c35afc6a1e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'section')
    # ### end Alembic commands ###
