"""Added group column

Revision ID: ab73ec4510cc
Revises: 10637c7d7537
Create Date: 2025-02-28 05:55:17.713026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab73ec4510cc'
down_revision: Union[str, None] = '10637c7d7537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'group')
    # ### end Alembic commands ###
