"""Added designation column

Revision ID: c35afc6a1e4d
Revises: 10637c7d7537
Create Date: 2025-02-28 05:45:38.696558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35afc6a1e4d'
down_revision: Union[str, None] = '10637c7d7537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'designation')
    # ### end Alembic commands ###
